#!/bin/sh

function get_pipeline() {
   export SEQ_PRISMS_BIN=/dataset/gseq_processing/active/bin/melseq_prism/seq_prisms 
   export MELSEQ_PRISM_BIN=/dataset/gseq_processing/active/bin/melseq_prism
   export GBS_PRISM_BIN=/dataset/gseq_processing/active/bin/gbs_prism

   cd $MELSEQ_PRISM_BIN 
   melseq_version=$1
   echo "preparing to run pipeline version $melseq_version (press enter to continue)"
   read answer
   is_alpha=`echo $melseq_version | grep alpha`
   if [ ! $is_alpha ]; then 
      git checkout -q $melseq_version  
      if [ $? != 0 ]; then
         echo "unable to checkout pipeline version $melseq_version"
         exit 1
      fi
      exec ./_run_melseq $melseq_version
   else
      echo "(no checkout for alpha versions, just running in current branch)"
      exec ./_run_melseq $melseq_version 
   fi
}

get_pipeline v0.0.1-alpha
