#!/bin/bash -e

#SBATCH -J $tardis_job_moniker
#SBATCH -A $tardis_account_moniker        # Project Account
#SBATCH --time=240:00:00            # Walltime
#SBATCH --ntasks=1                 # number of parallel processes
#SBATCH --ntasks-per-socket=1      # number of processes allowed on a socket
#SBATCH --cpus-per-task=8          #number of threads per process
#SBATCH --mem-per-cpu=4G  # will be initialised by script
#SBATCH --partition=inv-iranui-fast,inv-iranui,inv-blade-g8,inv-blade-g8-fast,inv-bigmem,inv-bigmem-fast   # Use nodes in any partition except bigmem
#SBATCH --array=$array_start-$array_stop%40          # Iterate 1 to N, but only run up to 80 concurrent runs at once
#SBATCH --error=$hpcdir/run-%A_%a.stderr
#SBATCH --output=$hpcdir/run-%A_%a.stdout

srun $hpcdir/slurm_array_shim.sh ${SLURM_ARRAY_TASK_ID}
